[package]
name = "diff-test"
authors = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
clap = { version = "^4.4", features = ["derive"] }
ethers = { workspace = true }
