name: test

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
    branches:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          prefix-key: v1-rust

      - name: Check forge version
        run: |
          nix develop --accept-flake-config -c which forge
          nix develop --accept-flake-config -c forge --version

      - name: Format check
        run: nix develop --accept-flake-config -c pre-commit run forge-fmt --all-files

      - name: Build non-test contracts without warnings
        run: nix develop --accept-flake-config -c forge build --skip test --deny-warnings

      - name: Build all contracts
        run: nix develop --accept-flake-config -c forge build

      - name: Run tests
        run: |
          nix develop --accept-flake-config -c cargo build --bin diff-test-bn254 --release
          nix develop --accept-flake-config -c forge test -vvv
